// PDFTextExtractor — MuPDF-parity structured text extraction on CoreGraphics.
//
// Why not PDFKit: the txn_store parsers cluster words by exact x/y coordinates
// (round(y0/3), dy<=3, column cutoffs at x=90/268/312/372) and the contract's
// expected JSONs were generated by pymupdf/MuPDF. PDFKit's characterBounds
// interleaves rotated watermarks with body text and reports glyph-ink bounds,
// which breaks clustering. This extractor re-implements MuPDF's stext device
// (source/fitz/stext-device.c @ 1.29) on top of CGPDFScanner:
//   * per-glyph quads from font ascender/descender and the text matrix
//   * line assembly with SPACE_DIST/SPACE_MAX_DIST/BASE_MAX_DIST heuristics
//   * synthetic space insertion for intra-line gaps
//   * fake-bold dedup (same char re-shown within 0.1em)
//   * glyphs entirely outside the mediabox are dropped
// Geometry is cast to Float32 at emission to mirror MuPDF's float pipeline.
import Foundation
import CoreGraphics

// MuPDF stext-device.c constants
private let SPACE_DIST = 0.15
private let SPACE_MAX_DIST = 0.8
private let BASE_MAX_DIST = 0.8
private let FAKE_BOLD_MAX_DIST = 0.1

struct Matrix2D {
    var a = 1.0, b = 0.0, c = 0.0, d = 1.0, e = 0.0, f = 0.0
    static let identity = Matrix2D()

    static func * (l: Matrix2D, r: Matrix2D) -> Matrix2D {
        // fz_concat(l, r): result = l × r (apply l first)
        Matrix2D(a: l.a * r.a + l.b * r.c,
                 b: l.a * r.b + l.b * r.d,
                 c: l.c * r.a + l.d * r.c,
                 d: l.c * r.b + l.d * r.d,
                 e: l.e * r.a + l.f * r.c + r.e,
                 f: l.e * r.b + l.f * r.d + r.f)
    }
    func transformPoint(_ x: Double, _ y: Double) -> (Double, Double) {
        (x * a + y * c + e, x * b + y * d + f)
    }
    func transformVector(_ x: Double, _ y: Double) -> (Double, Double) {
        (x * a + y * c, x * b + y * d)
    }
    var expansion: Double { (abs(a * d - b * c)).squareRoot() }
    static func translate(_ tx: Double, _ ty: Double) -> Matrix2D {
        Matrix2D(a: 1, b: 0, c: 0, d: 1, e: tx, f: ty)
    }
}

/// One extracted character (PDF-space coordinates, y up).
struct SChar {
    var c: Int32                 // unicode scalar (first scalar if multi)
    var text: String             // full unicode text for the char
    var quadX0, quadY0, quadX1, quadY1: Double  // bbox of quad, PDF space
    var originX, originY: Double
    var size: Double
    var font: String
}

final class SLineBuf {
    var dirX: Double, dirY: Double
    var wmode: Int
    var chars: [SChar] = []
    init(dirX: Double, dirY: Double, wmode: Int) {
        self.dirX = dirX; self.dirY = dirY; self.wmode = wmode
    }
}

public struct PDFWord {
    public let x0, y0, x1, y1: Double   // top-left-origin page coordinates
    public let text: String
}

public struct ExtractedPage {
    public let width: Double
    public let height: Double
    public let words: [PDFWord]
    public let text: String
}

// ------------------------------------------------------------------ assembler

final class StextAssembler {
    var lines: [SLineBuf] = []
    var curLine: SLineBuf? = nil
    var penX = 0.0, penY = 0.0
    var lagPenX = 0.0, lagPenY = 0.0
    var lastChar: Int32 = 0
    var clipRect: CGRect   // mediabox ∩ scissor test target (PDF space)

    init(mediaBox: CGRect) {
        self.clipRect = mediaBox
    }

    func addChar(font: PDFFont, text: String, trm: Matrix2D, adv: Double, clip: CGRect?) {
        guard let first = text.unicodeScalars.first else { return }
        let scalars = Array(text.unicodeScalars)
        addScalar(font: font, c: Int32(first.value), text: String(Character(first)),
                  trm: trm, adv: adv, hasGlyph: true, clip: clip)
        // extra scalars from multi-char ToUnicode mappings ride along zero-width
        for sc in scalars.dropFirst() {
            addScalar(font: font, c: Int32(sc.value), text: String(Character(sc)),
                      trm: trm, adv: 0, hasGlyph: false, clip: clip)
        }
    }

    private func addScalar(font: PDFFont, c: Int32, text: String, trm: Matrix2D,
                           adv: Double, hasGlyph: Bool, clip: CGRect?) {
        // dir/ndir/size/p/q exactly as fz_add_stext_char_imp (wmode 0)
        let (dirX, dirY) = trm.transformVector(1, 0)
        let dlen = (dirX * dirX + dirY * dirY).squareRoot()
        let (ndirX, ndirY) = dlen > 0 ? (dirX / dlen, dirY / dlen) : (1, 0)
        let size = trm.expansion
        let pX = trm.e, pY = trm.f
        let qX = trm.e + adv * dirX
        let qY = trm.f + adv * dirY

        // no-glyph continuation scalars: append in place without advancing the pen
        if let cur = curLine, !hasGlyph {
            appendChar(cur, font: font, c: c, text: text, trm: trm,
                       pX: penX, pY: penY, qX: penX, qY: penY, size: size)
            lastChar = c
            return
        }

        // clip: drop glyphs entirely outside mediabox ∩ scissor (true quad test,
        // matching fz_glyph_entirely_outside_box — the quad includes the
        // ascender/descender extents, which matters for rotated watermarks)
        let effClip = clip.map { clipRect.intersection($0) } ?? clipRect
        if !effClip.isNull {
            let (aX, aY) = trm.transformVector(0, font.ascender)
            let (dX, dY) = trm.transformVector(0, font.descender)
            let xs = [pX + dX, pX + aX, qX + dX, qX + aX]
            let ys = [pY + dY, pY + aY, qY + dY, qY + aY]
            let quadBox = CGRect(x: xs.min()!, y: ys.min()!,
                                 width: xs.max()! - xs.min()!, height: ys.max()! - ys.min()!)
            if !effClip.intersects(quadBox) {
                return
            }
        }

        var newLine = true
        var addSpace = 0

        if let cur = curLine, cur.wmode == 0, ndirX * cur.dirX + ndirY * cur.dirY >= 0.999 {
            // fake-bold dedup: same char re-shown virtually in place
            let fbDist = ((pX - lagPenX) * (pX - lagPenX) + (pY - lagPenY) * (pY - lagPenY)).squareRoot() / size
            if fbDist < FAKE_BOLD_MAX_DIST, c == lastChar { return }

            let deltaX = pX - penX, deltaY = pY - penY
            let spacing = (ndirX * deltaX + ndirY * deltaY) / size
            let baseOffset = (-ndirY * deltaX + ndirX * deltaY) / size

            if abs(baseOffset) < BASE_MAX_DIST {
                if abs(spacing) < SPACE_DIST {
                    newLine = false
                } else if spacing < 0, spacing > -SPACE_MAX_DIST {
                    newLine = false
                } else if spacing > 0, spacing < SPACE_MAX_DIST {
                    if mayAddSpace(lastChar) { addSpace = 1 }
                    newLine = false
                } else {
                    newLine = true
                }
            } else {
                newLine = true
            }
        }

        if newLine || curLine == nil {
            let line = SLineBuf(dirX: ndirX, dirY: ndirY, wmode: 0)
            lines.append(line)
            curLine = line
        }
        guard let cur = curLine else { return }

        if c != 32, addSpace > 0 {
            appendChar(cur, font: font, c: 32, text: " ", trm: trm,
                       pX: penX, pY: penY, qX: pX, qY: pY, size: size)
        }
        appendChar(cur, font: font, c: c, text: text, trm: trm,
                   pX: pX, pY: pY, qX: qX, qY: qY, size: size)

        lastChar = c
        lagPenX = pX; lagPenY = pY
        penX = qX; penY = qY
    }

    private func mayAddSpace(_ last: Int32) -> Bool {
        last != 32 && (last < 0x700 || (last >= 0x2000 && last <= 0x20CF))
    }

    private func appendChar(_ line: SLineBuf, font: PDFFont, c: Int32, text: String,
                            trm: Matrix2D, pX: Double, pY: Double, qX: Double, qY: Double,
                            size: Double) {
        // quad corners: p/q offset by trm-transformed (0, ascender) and (0, descender)
        let (aX, aY) = trm.transformVector(0, font.ascender)
        let (dX, dY) = trm.transformVector(0, font.descender)
        let xs = [pX + dX, pX + aX, qX + dX, qX + aX].map { Double(Float($0)) }
        let ys = [pY + dY, pY + aY, qY + dY, qY + aY].map { Double(Float($0)) }
        line.chars.append(SChar(c: c, text: text,
                                quadX0: xs.min()!, quadY0: ys.min()!,
                                quadX1: xs.max()!, quadY1: ys.max()!,
                                originX: Double(Float(pX)), originY: Double(Float(pY)),
                                size: Double(Float(size)), font: font.baseFont))
    }

    /// Finish: produce top-origin words + text like pymupdf get_text("words"/"text").
    func finish(mediaBox: CGRect) -> ExtractedPage {
        let h = Double(mediaBox.maxY)
        let xOff = Double(mediaBox.minX)
        var words: [PDFWord] = []
        var text = ""
        for line in lines {
            var lineText = ""
            var wordText = ""
            var wx0 = 0.0, wy0 = 0.0, wx1 = 0.0, wy1 = 0.0
            var started = false
            func flushWord() {
                if started, !wordText.isEmpty {
                    words.append(PDFWord(x0: wx0 - xOff, y0: h - wy1, x1: wx1 - xOff, y1: h - wy0,
                                         text: wordText))
                }
                wordText = ""; started = false
            }
            for ch in line.chars {
                lineText += ch.text
                if let sc = Unicode.Scalar(UInt32(ch.c)), Character(sc).isWhitespace {
                    flushWord()
                } else {
                    if !started {
                        wx0 = ch.quadX0; wy0 = ch.quadY0; wx1 = ch.quadX1; wy1 = ch.quadY1
                        started = true
                    } else {
                        wx0 = min(wx0, ch.quadX0); wy0 = min(wy0, ch.quadY0)
                        wx1 = max(wx1, ch.quadX1); wy1 = max(wy1, ch.quadY1)
                    }
                    wordText += ch.text
                }
            }
            flushWord()
            text += lineText + "\n"
        }
        return ExtractedPage(width: Double(mediaBox.width), height: Double(mediaBox.height),
                             words: words, text: text)
    }
}

// ------------------------------------------------------------------ interpreter

final class PDFPageInterpreter {
    struct GState {
        var ctm = Matrix2D.identity
        var clip: CGRect? = nil
    }
    struct TState {
        var font: PDFFont? = nil
        var fontSize = 0.0
        var charSpace = 0.0     // Tc
        var wordSpace = 0.0     // Tw
        var hscale = 1.0        // Tz / 100
        var leading = 0.0       // TL
        var rise = 0.0          // Ts
        var tm = Matrix2D.identity
        var tlm = Matrix2D.identity
    }

    var gsStack: [GState] = []
    var gs = GState()
    var ts = TState()
    var fonts: [String: PDFFont] = [:]
    var fontCache: [String: PDFFont] = [:]   // by resource name per page
    let assembler: StextAssembler
    var resourcesStack: [CGPDFDictionaryRef] = []
    var csStack: [CGPDFContentStreamRef] = []
    // pending path rects for clip tracking (`re ... W n`)
    var pathRects: [CGRect] = []
    var pendingClip = false

    init(assembler: StextAssembler) {
        self.assembler = assembler
    }

    var currentResources: CGPDFDictionaryRef? { resourcesStack.last }

    func font(named name: String) -> PDFFont? {
        if let f = fontCache[name] { return f }
        guard let res = currentResources else { return nil }
        var fontsDict: CGPDFDictionaryRef? = nil
        guard CGPDFDictionaryGetDictionary(res, "Font", &fontsDict), let fontsDict else { return nil }
        var fdict: CGPDFDictionaryRef? = nil
        guard CGPDFDictionaryGetDictionary(fontsDict, name, &fdict), let fdict else { return nil }
        let f = PDFFont(dict: fdict)
        fontCache[name] = f
        return f
    }

    // ---- text showing

    func showText(_ bytes: [UInt8]) {
        guard let font = ts.font else { return }
        for code in bytes {
            let codeI = Int(code)
            let w0 = font.advance(for: codeI)
            let uni = font.unicode(for: codeI)
            let tsm = Matrix2D(a: ts.fontSize * ts.hscale, b: 0, c: 0,
                               d: ts.fontSize, e: 0, f: ts.rise)
            let trm = tsm * ts.tm * gs.ctm
            assembler.addChar(font: font, text: uni, trm: trm, adv: w0, clip: gs.clip)
            let tx = (w0 * ts.fontSize + ts.charSpace + (code == 32 ? ts.wordSpace : 0)) * ts.hscale
            ts.tm = Matrix2D.translate(tx, 0) * ts.tm
        }
    }

    func showTextAdjusted(_ items: [TJItem]) {
        for item in items {
            switch item {
            case .string(let bytes):
                showText(bytes)
            case .number(let n):
                let tx = (-n / 1000.0) * ts.fontSize * ts.hscale
                ts.tm = Matrix2D.translate(tx, 0) * ts.tm
            }
        }
    }

    enum TJItem {
        case string([UInt8])
        case number(Double)
    }

    func nextLine() {   // T*
        ts.tlm = Matrix2D.translate(0, -ts.leading) * ts.tlm
        ts.tm = ts.tlm
    }

    // ---- clip bookkeeping

    func paintPathEnd() {
        if pendingClip {
            var r: CGRect? = nil
            for rect in pathRects {
                let (x0, y0) = gs.ctm.transformPoint(Double(rect.minX), Double(rect.minY))
                let (x1, y1) = gs.ctm.transformPoint(Double(rect.maxX), Double(rect.maxY))
                let dev = CGRect(x: min(x0, x1), y: min(y0, y1),
                                 width: abs(x1 - x0), height: abs(y1 - y0))
                r = r.map { $0.union(dev) } ?? dev
            }
            if let r {
                gs.clip = gs.clip.map { $0.intersection(r) } ?? r
            }
            pendingClip = false
        }
        pathRects = []
    }
}

// ------------------------------------------------------------------ scanner glue

public enum PDFTextExtractorError: Error {
    case cannotOpen(String)
}

public final class PDFTextExtractor {
    let doc: CGPDFDocument
    public let pageCount: Int
    var cache: [Int: ExtractedPage] = [:]

    public init(path: String) throws {
        guard let doc = CGPDFDocument(URL(fileURLWithPath: path) as CFURL) else {
            throw PDFTextExtractorError.cannotOpen(path)
        }
        self.doc = doc
        self.pageCount = doc.numberOfPages
    }

    /// Document Info metadata (pymupdf doc.metadata analog; keys lowercased pymupdf-style).
    public var metadata: [String: String] {
        var out: [String: String] = [:]
        guard let info = doc.info else { return out }
        for (pdfKey, outKey) in [("Title", "title"), ("Author", "author"), ("Subject", "subject"),
                                 ("Keywords", "keywords"), ("Creator", "creator"),
                                 ("Producer", "producer")] {
            var strRef: CGPDFStringRef? = nil
            if CGPDFDictionaryGetString(info, pdfKey, &strRef), let strRef,
               let s = CGPDFStringCopyTextString(strRef) {
                out[outKey] = s as String
            }
        }
        return out
    }

    public func page(_ index: Int) -> ExtractedPage? {   // 0-based
        if let c = cache[index] { return c }
        guard index >= 0, index < pageCount, let page = doc.page(at: index + 1),
              let pageDict = page.dictionary else { return nil }
        let mediaBox = page.getBoxRect(.mediaBox)
        let assembler = StextAssembler(mediaBox: mediaBox)
        let interp = PDFPageInterpreter(assembler: assembler)
        if let res = inheritedResources(pageDict) {
            interp.resourcesStack.append(res)
        }

        let contentStream = CGPDFContentStreamCreateWithPage(page)
        interp.csStack.append(contentStream)
        let scanner = CGPDFScannerCreate(contentStream, pdfSharedOperatorTable, Unmanaged.passUnretained(interp).toOpaque())
        CGPDFScannerScan(scanner)
        CGPDFScannerRelease(scanner)
        CGPDFContentStreamRelease(contentStream)

        let result = assembler.finish(mediaBox: mediaBox)
        cache[index] = result
        return result
    }

    /// Page Resources with /Parent-chain inheritance.
    private func inheritedResources(_ pageDict: CGPDFDictionaryRef) -> CGPDFDictionaryRef? {
        var d: CGPDFDictionaryRef? = pageDict
        while let cur = d {
            var res: CGPDFDictionaryRef? = nil
            if CGPDFDictionaryGetDictionary(cur, "Resources", &res) { return res }
            var parent: CGPDFDictionaryRef? = nil
            if CGPDFDictionaryGetDictionary(cur, "Parent", &parent) { d = parent } else { d = nil }
        }
        return nil
    }

}

// ------------------------------------------------------------------ scanner callbacks
// File-scope (not type members): closures passed to CGPDFOperatorTableSetCallback
// must convert to C function pointers, so they may only reference file-scope
// functions and globals — never type members (Swift counts those as captures).

private func interp(_ info: UnsafeMutableRawPointer?) -> PDFPageInterpreter {
    Unmanaged<PDFPageInterpreter>.fromOpaque(info!).takeUnretainedValue()
}

private func popNumber(_ s: CGPDFScannerRef) -> Double {
    var v: CGPDFReal = 0
    if CGPDFScannerPopNumber(s, &v) { return Double(v) }
    return 0
}

private func popString(_ s: CGPDFScannerRef) -> [UInt8] {
    var str: CGPDFStringRef? = nil
    guard CGPDFScannerPopString(s, &str), let str else { return [] }
    let len = CGPDFStringGetLength(str)
    guard let ptr = CGPDFStringGetBytePtr(str) else { return [] }
    return Array(UnsafeBufferPointer(start: ptr, count: len))
}

let pdfSharedOperatorTable: CGPDFOperatorTableRef = makeOperatorTable()

private func makeOperatorTable() -> CGPDFOperatorTableRef {
        let table = CGPDFOperatorTableCreate()!

        CGPDFOperatorTableSetCallback(table, "q") { s, info in
            let ip = interp(info); ip.gsStack.append(ip.gs)
        }
        CGPDFOperatorTableSetCallback(table, "Q") { s, info in
            let ip = interp(info); if let g = ip.gsStack.popLast() { ip.gs = g }
        }
        CGPDFOperatorTableSetCallback(table, "cm") { s, info in
            let ip = interp(info)
            let f = popNumber(s), e = popNumber(s), d = popNumber(s)
            let c = popNumber(s), b = popNumber(s), a = popNumber(s)
            ip.gs.ctm = Matrix2D(a: a, b: b, c: c, d: d, e: e, f: f) * ip.gs.ctm
        }
        CGPDFOperatorTableSetCallback(table, "BT") { s, info in
            let ip = interp(info); ip.ts.tm = .identity; ip.ts.tlm = .identity
        }
        CGPDFOperatorTableSetCallback(table, "ET") { _, _ in }
        CGPDFOperatorTableSetCallback(table, "Tf") { s, info in
            let ip = interp(info)
            let size = popNumber(s)
            var namePtr: UnsafePointer<Int8>? = nil
            if CGPDFScannerPopName(s, &namePtr), let p = namePtr {
                ip.ts.font = ip.font(named: String(cString: p))
            }
            ip.ts.fontSize = size
        }
        CGPDFOperatorTableSetCallback(table, "Td") { s, info in
            let ip = interp(info)
            let ty = popNumber(s), tx = popNumber(s)
            ip.ts.tlm = Matrix2D.translate(tx, ty) * ip.ts.tlm
            ip.ts.tm = ip.ts.tlm
        }
        CGPDFOperatorTableSetCallback(table, "TD") { s, info in
            let ip = interp(info)
            let ty = popNumber(s), tx = popNumber(s)
            ip.ts.leading = -ty
            ip.ts.tlm = Matrix2D.translate(tx, ty) * ip.ts.tlm
            ip.ts.tm = ip.ts.tlm
        }
        CGPDFOperatorTableSetCallback(table, "Tm") { s, info in
            let ip = interp(info)
            let f = popNumber(s), e = popNumber(s), d = popNumber(s)
            let c = popNumber(s), b = popNumber(s), a = popNumber(s)
            ip.ts.tlm = Matrix2D(a: a, b: b, c: c, d: d, e: e, f: f)
            ip.ts.tm = ip.ts.tlm
        }
        CGPDFOperatorTableSetCallback(table, "T*") { s, info in
            interp(info).nextLine()
        }
        CGPDFOperatorTableSetCallback(table, "TL") { s, info in
            let ip = interp(info); ip.ts.leading = popNumber(s)
        }
        CGPDFOperatorTableSetCallback(table, "Tc") { s, info in
            let ip = interp(info); ip.ts.charSpace = popNumber(s)
        }
        CGPDFOperatorTableSetCallback(table, "Tw") { s, info in
            let ip = interp(info); ip.ts.wordSpace = popNumber(s)
        }
        CGPDFOperatorTableSetCallback(table, "Tz") { s, info in
            let ip = interp(info); ip.ts.hscale = popNumber(s) / 100.0
        }
        CGPDFOperatorTableSetCallback(table, "Ts") { s, info in
            let ip = interp(info); ip.ts.rise = popNumber(s)
        }
        CGPDFOperatorTableSetCallback(table, "Tj") { s, info in
            interp(info).showText(popString(s))
        }
        CGPDFOperatorTableSetCallback(table, "'") { s, info in
            let ip = interp(info)
            let bytes = popString(s)
            ip.nextLine()
            ip.showText(bytes)
        }
        CGPDFOperatorTableSetCallback(table, "\"") { s, info in
            let ip = interp(info)
            let bytes = popString(s)
            ip.ts.charSpace = popNumber(s)
            ip.ts.wordSpace = popNumber(s)
            ip.nextLine()
            ip.showText(bytes)
        }
        CGPDFOperatorTableSetCallback(table, "TJ") { s, info in
            let ip = interp(info)
            var arr: CGPDFArrayRef? = nil
            guard CGPDFScannerPopArray(s, &arr), let arr else { return }
            var items: [PDFPageInterpreter.TJItem] = []
            for i in 0..<CGPDFArrayGetCount(arr) {
                var strRef: CGPDFStringRef? = nil
                var num: CGPDFReal = 0
                var inum: CGPDFInteger = 0
                if CGPDFArrayGetString(arr, i, &strRef), let strRef {
                    let len = CGPDFStringGetLength(strRef)
                    if let ptr = CGPDFStringGetBytePtr(strRef) {
                        items.append(.string(Array(UnsafeBufferPointer(start: ptr, count: len))))
                    }
                } else if CGPDFArrayGetNumber(arr, i, &num) {
                    items.append(.number(Double(num)))
                } else if CGPDFArrayGetInteger(arr, i, &inum) {
                    items.append(.number(Double(inum)))
                }
            }
            ip.showTextAdjusted(items)
        }
        // path construction (only rects matter, for clip tracking)
        CGPDFOperatorTableSetCallback(table, "re") { s, info in
            let ip = interp(info)
            let h = popNumber(s), w = popNumber(s), y = popNumber(s), x = popNumber(s)
            ip.pathRects.append(CGRect(x: x, y: y, width: w, height: h))
        }
        CGPDFOperatorTableSetCallback(table, "W") { _, info in interp(info).pendingClip = true }
        CGPDFOperatorTableSetCallback(table, "W*") { _, info in interp(info).pendingClip = true }
        CGPDFOperatorTableSetCallback(table, "n") { _, info in interp(info).paintPathEnd() }
        CGPDFOperatorTableSetCallback(table, "f") { _, info in interp(info).paintPathEnd() }
        CGPDFOperatorTableSetCallback(table, "F") { _, info in interp(info).paintPathEnd() }
        CGPDFOperatorTableSetCallback(table, "f*") { _, info in interp(info).paintPathEnd() }
        CGPDFOperatorTableSetCallback(table, "S") { _, info in interp(info).paintPathEnd() }
        CGPDFOperatorTableSetCallback(table, "s") { _, info in interp(info).paintPathEnd() }
        CGPDFOperatorTableSetCallback(table, "B") { _, info in interp(info).paintPathEnd() }
        CGPDFOperatorTableSetCallback(table, "B*") { _, info in interp(info).paintPathEnd() }
        CGPDFOperatorTableSetCallback(table, "b") { _, info in interp(info).paintPathEnd() }
        CGPDFOperatorTableSetCallback(table, "b*") { _, info in interp(info).paintPathEnd() }
        // Form XObjects
        CGPDFOperatorTableSetCallback(table, "Do") { s, info in
            opDo(s, info)
        }
        return table
}

private func opDo(_ sOpt: CGPDFScannerRef?, _ info: UnsafeMutableRawPointer?) {
        guard let s = sOpt else { return }
        let ip = interp(info)
        var namePtr: UnsafePointer<Int8>? = nil
        guard CGPDFScannerPopName(s, &namePtr), let p = namePtr,
              let res = ip.currentResources else { return }
        let name = String(cString: p)
        var xobjs: CGPDFDictionaryRef? = nil
        guard CGPDFDictionaryGetDictionary(res, "XObject", &xobjs), let xobjs else { return }
        var stream: CGPDFStreamRef? = nil
        guard CGPDFDictionaryGetStream(xobjs, name, &stream), let stream else { return }
        guard let sdict = CGPDFStreamGetDictionary(stream) else { return }
        var subtypePtr: UnsafePointer<Int8>? = nil
        guard CGPDFDictionaryGetName(sdict, "Subtype", &subtypePtr), let sp = subtypePtr,
              String(cString: sp) == "Form" else { return }

        // save graphics state; apply /Matrix; push form resources
        let savedGS = ip.gs
        let savedTS = ip.ts
        var mArr: CGPDFArrayRef? = nil
        if CGPDFDictionaryGetArray(sdict, "Matrix", &mArr), let mArr,
           CGPDFArrayGetCount(mArr) == 6 {
            var vals = [Double](repeating: 0, count: 6)
            for i in 0..<6 {
                var v: CGPDFReal = 0
                var iv: CGPDFInteger = 0
                if CGPDFArrayGetNumber(mArr, i, &v) { vals[i] = Double(v) }
                else if CGPDFArrayGetInteger(mArr, i, &iv) { vals[i] = Double(iv) }
            }
            ip.gs.ctm = Matrix2D(a: vals[0], b: vals[1], c: vals[2],
                                 d: vals[3], e: vals[4], f: vals[5]) * ip.gs.ctm
        }
        var formRes: CGPDFDictionaryRef? = nil
        let pushedRes = CGPDFDictionaryGetDictionary(sdict, "Resources", &formRes)
        if pushedRes, let formRes { ip.resourcesStack.append(formRes) }
        let savedFontCache = ip.fontCache
        if pushedRes { ip.fontCache = [:] }

        guard let parentCS = ip.csStack.last else { return }
        let cs = CGPDFContentStreamCreateWithStream(stream, sdict, parentCS)
        ip.csStack.append(cs)
        let scanner2 = CGPDFScannerCreate(cs, pdfSharedOperatorTable, Unmanaged.passUnretained(ip).toOpaque())
        CGPDFScannerScan(scanner2)
        CGPDFScannerRelease(scanner2)
        ip.csStack.removeLast()
        CGPDFContentStreamRelease(cs)

        if pushedRes { ip.resourcesStack.removeLast(); ip.fontCache = savedFontCache }
        ip.gs = savedGS
        ip.ts = savedTS
}
